### ISSUE TITLE
6's tiles don't fall down into buckets if Swap is used to place the tile right above the bucket. Game still completes.

### ISSUE THREAD

**Issue by bckawuh** [arthurlockman/sixeswild#18]

**Comment by bckawuh** [comment]
Also, should Swap change the positions of 2 tiles from anywhere on the board, or only 2 neighboring tiles?

**Comment by arthurlockman** [comment]
I suspect this is a bug in the way the screen refreshes - will look into it.

**Comment by arthurlockman** [comment]
Fixed in 366ab18.
