### ISSUE TITLE
Choose to end game that has already been won

### ISSUE THREAD

**Issue by bckawuh** [arthurlockman/sixeswild#20]
Can we allow players to end the game on their own, while still winning? Like if they get enough points for Puzzle but still have 30 moves left, and they just want to go to the next level already.

**Comment by arthurlockman** [comment]
Not sure if this is in the scope - the levels only end when their end condition is met. If they still have 30 moves left in a puzzle level then they need to finish. Perhaps we shouldn't make levels that have 50 moves so that completing them is actually difficult?

**Comment by bckawuh** [comment]
I think that would be a good thing to do.

**Comment by arthurlockman** [comment]
I think the way we fix this is to not give levels such absurdly high numbers of moves. The game doesn't need to support this. A lot of things get fired when the level completes, and clicking the back button shouldn't constitute the game completing.
